import React, { useEffect } from 'react'
import { Navbar } from '../components/marketing/Navbar'
import { Footer } from '../components/marketing/Footer'
import { useNavigate } from 'react-router-dom'

export const Terms: React.FC = () => {
  const navigate = useNavigate()

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  return (
    <div className="min-h-screen bg-slate-950 text-slate-300 font-sans selection:bg-cyan-500 selection:text-black">
      <Navbar onSubscribe={() => navigate('/checkout?plan=pro')} />
      
      <main className="pt-32 pb-24 px-6">
        <div className="max-w-4xl mx-auto bg-slate-900/50 border border-slate-800 rounded-3xl p-8 md:p-16 shadow-2xl backdrop-blur-sm">
          <div className="mb-12 border-b border-slate-800 pb-8">
            <h1 className="text-4xl md:text-5xl font-black text-slate-100 mb-4 tracking-tight">Terms of Service</h1>
            <p className="text-slate-400 text-lg">Effective Date: October 15, 2026</p>
          </div>

          <div className="space-y-10 text-lg leading-relaxed">
            
            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">1. Acceptance of Terms</h2>
              <p className="mb-4">
                These Terms of Service ("Terms") represent a legally binding contract between OmniAgent Inc. ("OmniAgent", "we", "us", or "our") and you, the enterprise customer ("Customer", "you", or "your"). By creating an account or utilizing our autonomous multi-agent systems and GraphRAG platform (the "Services"), you acknowledge that you have read, understood, and agreed to be bound by these Terms.
              </p>
              <p>
                If you are entering into these Terms on behalf of an entity, such as your employer or the company you work for, you represent that you have the legal authority to bind that entity.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">2. Provision of Services</h2>
              <p className="mb-4">
                OmniAgent provides an enterprise-grade AI ecosystem. We grant you a non-exclusive, non-transferable, revocable right to access and use the Services during your subscription term solely for your internal business operations. 
              </p>
              <p>
                We reserve the right to modify, upgrade, or deprecate features of the Services, provided such changes do not materially degrade the core functionality you have subscribed to. In the event of material deprecations, we will provide at least 30 days prior written notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">3. Customer Obligations and Acceptable Use</h2>
              <p className="mb-4">You agree not to misuse the Services. Specifically, you shall not:</p>
              <ul className="list-disc pl-6 space-y-2 text-slate-400">
                <li>Reverse engineer, decompile, or disassemble the OmniAgent platform.</li>
                <li>Utilize the Services to generate malicious code, engage in cyber-attacks, or violate any applicable laws.</li>
                <li>Upload sensitive health data (e.g., HIPAA-regulated PHI) unless a specific Business Associate Agreement (BAA) has been executed with OmniAgent.</li>
                <li>Attempt to bypass or circumvent the PostgreSQL Row-Level Security (RLS) constraints or any other security mechanisms.</li>
              </ul>
              <p className="mt-4 text-sm text-slate-500 italic">Violations of this Acceptable Use Policy may result in immediate suspension or termination of your account without a refund.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">4. Intellectual Property Rights</h2>
              <p className="mb-4">
                <strong>Your Data:</strong> You retain all ownership and intellectual property rights to the data, documents, and APIs you integrate into OmniAgent (the "Customer Data"). We claim absolutely no ownership over your inputs or the specific outputs generated by our agents acting on your behalf.
              </p>
              <p>
                <strong>Our Platform:</strong> OmniAgent retains all right, title, and interest in the Services, including our proprietary GraphRAG orchestration algorithms, agent swarm mechanics, system architectures, and UI/UX designs.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">5. Confidentiality and Security</h2>
              <p className="mb-4">
                Both parties agree to hold each other's Confidential Information in strict confidence. OmniAgent treats all Customer Data as strictly confidential. As detailed in our Privacy Policy, your data is never used to train global AI models. We implement enterprise-grade security protocols (SOC2 compliance, end-to-end encryption) to safeguard your information against unauthorized access.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">6. Payment and Billing</h2>
              <p className="mb-4">
                Fees for the Services are billed in advance on a recurring schedule (monthly or annually) according to the pricing tier you selected. All fees are non-refundable unless otherwise specified. Failure to pay outstanding invoices within 15 days may result in suspension of your API access.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">7. Limitation of Liability</h2>
              <p className="mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL OMNIAGENT BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS OR LOST DATA, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR INABILITY TO USE THE SERVICES.
              </p>
              <p>
                Our total cumulative liability to you for any claims arising under these Terms shall not exceed the total amount paid by you to OmniAgent during the 12 months immediately preceding the event giving rise to the liability.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-200 mb-4">8. Termination</h2>
              <p className="mb-4">
                Either party may terminate these Terms for cause upon 30 days written notice of a material breach if such breach remains uncured at the expiration of the notice period. Upon termination, all rights granted to you will immediately cease, and we will permanently delete your Customer Data in accordance with our data retention policies.
              </p>
            </section>

          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
